asset_path: /home/usainbot/Desktop/Vittorio_Cammarota/Reinforcement_Learning/isaac_drone_racer/assets/a2r_gate/meshes/a2r_gate.glb
usd_dir: /home/usainbot/Desktop/Vittorio_Cammarota/Reinforcement_Learning/isaac_drone_racer/assets/a2r_gate
usd_file_name: a2r_gate.usd
force_usd_conversion: true
make_instanceable: false
mass_props:
  mass: 10.0
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
collision_approximation: convexDecomposition
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-06-23 at 17:00:04.
##
